apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vm

helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: victoria-logs-cluster-0.0.17
    releaseName: vlc
    valuesFile: values.yaml
    namespace: vm